apiVersion : apps/v1
kind: Deployment
metadata:
  name: rental
  labels:
    app : k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      project: rent
  template:
    metadata:
      labels:
        project: rent   
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: db-secrets
      containers:
        - name : rent-web
          image: eu.gcr.io/terraform-319316/rental-test:init
          resources: {}
          env: 
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key : db_host
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key : db_user
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key : db_pass
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key : db_name      
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: rental-service
  labels:
    env  : test
spec:
  selector:
    project: rent
  ports:
    - name      : listener
      protocol  : TCP
      port      : 80  
      targetPort: 8080
  type: LoadBalancer
